---
# defaults file for discovery
defaults_hosts: 'all'
sudoers: "/etc/sudoers.d/sherlock"

list_build_agent:
  - { 'Host': sherlock5, 'HostName': 192.168.44.154 }
  - { 'Host': sherlock6, 'HostName': 192.168.44.98 }
  - { 'Host': sherlock7, 'HostName': 192.168.45.28 }
  - { 'Host': sherlock8, 'HostName': 192.168.45.29 }
  - { 'Host': sherlock9, 'HostName': 192.168.44.143 }
  - { 'Host': sherlock10, 'HostName': 192.168.44.220 }
  - { 'Host': dump, 'HostName': 192.168.44.84}

list_docker_servers:
  - 192.168.44.56
  - 192.168.45.28
  - 192.168.45.143

hostname_app1: "{% if base_domain is defined %}app1.{{ base_domain }}{% else %}{{ ansible_host }}{% endif %}"
add_key: |
  Host {{ customer }}-app1
    HostName = {{ hostname_app1 }}
    User = sherlock-agent
    IdentityFile = ~/.ssh/keys/{{customer}}.key

add_for_dump: |-
  {{ customer }})
      REMOTE_HOST={% if type_servers is defined and type_servers == "hostel" %}{{ name_master }}{% else %}{{ customer }}{% endif %}-app1

add_for_deploy_release: |4-
      {{ customer }})
      \t  REMOTE_HOST={% if type_servers is defined and type_servers == "hostel" %}{{ name_master }}{% else %}{{ customer }}{% endif %}-app1

